# Generated by Django 3.1.3 on 2020-11-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportgoods', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='image_url',
            field=models.ImageField(upload_to='gear'),
        ),
    ]
