# Generated by Django 3.1.3 on 2020-12-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportgoods', '0006_auto_20201123_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
