# Generated by Django 3.1.3 on 2020-12-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pridesport_auth', '0003_auto_20201207_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
