# Generated by Django 3.1.3 on 2020-11-12 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fight', 'fight'), ('fitness', 'fitness'), ('clothing', 'clothing'), ('unknown', 'Unknown')], default='unknown', max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gears.gear')),
            ],
        ),
    ]
