# Generated by Django 3.1.3 on 2020-12-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0005_auto_20201206_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='likes',
        ),
    ]
