# Generated by Django 3.1.3 on 2020-12-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0008_gear_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='created_by',
        ),
    ]
