# Generated by Django 3.1.3 on 2020-11-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportgoods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='Gear',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='pet',
            new_name='gear',
        ),
    ]
